export {default as Home} from "./pages/Home"
export {default as Collection} from "./pages/Collection"
export {default as About} from "./pages/About"
export {default as Cart} from "./pages/Cart"
export {default as Contact} from "./pages/Contact"
export {default as Orders} from "./pages/Orders"
// export {default as Login} from "./pages/Login"
export {default as PlaceOrder} from "./pages/PlaceOrder"
export {default as Product} from "./pages/Product"
export {default as Policy} from "./components/OurPolicy"
